### ISSUE TITLE
cpu_temp.py does not work under python3

### ISSUE THREAD

**Issue by dglaude** [pimoroni/blinkt#50] opened 2017-03-31 17:52 UTC
The title says it all.
PS: Works fine with python[2]
```
$ python3 cpu_temp.py
Traceback (most recent call last):
  File "cpu_temp.py", line 31, in <module>
    v = get_cpu_temperature() / 100.0
  File "cpu_temp.py", line 14, in get_cpu_temperature
    return float(output[output.index('=') + 1:output.rindex("'")])
TypeError: Type str doesn't support the buffer API
```

**Comment by Gadgetoid** [comment] 2017-04-03 12:14
Duplicate of #48

**Closed as completed by Gadgetoid** 2017-04-03 12:14 UTC
